name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - develop
      - support/production

stages:
- stage: build
  displayName: build
  variables:
    CI: true
  jobs:
    - job: mainbuild
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - powershell: |
          cd $(Build.SourcesDirectory)
          ls
        displayName: 'Listing Files'
      - task: CacheBeta@0
        inputs:
          key: $(Build.SourcesDirectory)/package.json
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: CACHE_RESTORED
        displayName: 'Cache Npm'
      - script: chmod +x $(Build.SourcesDirectory)/node_modules/react-scripts-ts
        condition: eq(variables.CACHE_RESTORED, 'true')
        displayName: 'Change perms'
      - powershell: |
          ls -l $(Build.SourcesDirectory)/node-modules/.bin/
        condition: eq(variables.CACHE_RESTORED, 'true')
        displayName: 'Checking perms'
      #install nodejs modules with npm
      - powershell: |
          rm -rf $(Build.SourcesDirectory)/node_modules
        displayName: 'Removing node_modules'
        condition: ne(variables.CACHE_RESTORED, 'true')
      - script: 'npm install'
        workingDirectory: '$(Build.SourcesDirectory)'
        displayName: 'npm install'
        condition: ne(variables.CACHE_RESTORED, 'true')
      #start unit tests
      #- script: 'npm test'
       # displayName: 'npm test'
        #workingDirectory: '$(Build.SourcesDirectory)'
      #build the solution
      - script: 'npm run build'
        displayName: 'npm run build'
        workingDirectory: '$(Build.SourcesDirectory)'
        continueOnError: true 
      - powershell: |
          cat /home/vsts/.npm/_logs/*.log
        displayName: 'List logs'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/build'
          ArtifactName: drop